# generated by datamodel-codegen:
#   filename:  openapi.yaml
#   timestamp: 2026-04-09T15:01:48+00:00

from __future__ import annotations

from enum import StrEnum
from typing import Annotated

from pydantic import AwareDatetime, BaseModel, EmailStr, Field


class SignupRequest(BaseModel):
    email: EmailStr
    password: Annotated[str, Field(min_length=8)]


class LoginRequest(BaseModel):
    email: EmailStr
    password: str


class AuthResponse(BaseModel):
    token: Annotated[str | None, Field(description="JWT token (valid for 6 hours)")] = (
        None
    )
    user_id: str | None = None
    team_id: str | None = None
    email: str | None = None


class CreateAPIKeyRequest(BaseModel):
    name: str | None = "Unnamed API Key"


class APIKeyResponse(BaseModel):
    id: str | None = None
    team_id: str | None = None
    name: str | None = None
    key_prefix: Annotated[
        str | None, Field(description='Display prefix (e.g. "wrn_ab12cd34...")')
    ] = None
    created_at: AwareDatetime | None = None
    last_used: AwareDatetime | None = None
    key: Annotated[
        str | None,
        Field(
            description="Full plaintext key. Only returned on creation, never again."
        ),
    ] = None


class CreateSandboxRequest(BaseModel):
    template: str | None = "minimal"
    vcpus: int | None = 1
    memory_mb: int | None = 512
    timeout_sec: Annotated[
        int | None,
        Field(
            description="Auto-pause TTL in seconds. The sandbox is automatically paused after this duration of inactivity (no exec or ping). 0 means no auto-pause.\n"
        ),
    ] = 0


class Status(StrEnum):
    pending = "pending"
    running = "running"
    paused = "paused"
    stopped = "stopped"
    error = "error"


class Sandbox(BaseModel):
    id: str | None = None
    status: Status | None = None
    template: str | None = None
    vcpus: int | None = None
    memory_mb: int | None = None
    timeout_sec: int | None = None
    guest_ip: str | None = None
    host_ip: str | None = None
    created_at: AwareDatetime | None = None
    started_at: AwareDatetime | None = None
    last_active_at: AwareDatetime | None = None
    last_updated: AwareDatetime | None = None


class CreateSnapshotRequest(BaseModel):
    sandbox_id: Annotated[
        str, Field(description="ID of the running sandbox to snapshot.")
    ]
    name: Annotated[
        str | None,
        Field(description="Name for the snapshot template. Auto-generated if omitted."),
    ] = None


class Type(StrEnum):
    base = "base"
    snapshot = "snapshot"


class Template(BaseModel):
    name: str | None = None
    type: Type | None = None
    vcpus: int | None = None
    memory_mb: int | None = None
    size_bytes: int | None = None
    created_at: AwareDatetime | None = None


class ExecRequest(BaseModel):
    cmd: str
    args: list[str] | None = None
    timeout_sec: int | None = 30


class Encoding(StrEnum):
    """
    Output encoding. "base64" when stdout/stderr contain binary data.
    """

    utf_8 = "utf-8"
    base64 = "base64"


class ExecResponse(BaseModel):
    sandbox_id: str | None = None
    cmd: str | None = None
    stdout: str | None = None
    stderr: str | None = None
    exit_code: int | None = None
    duration_ms: int | None = None
    encoding: Annotated[
        Encoding | None,
        Field(
            description='Output encoding. "base64" when stdout/stderr contain binary data.'
        ),
    ] = None


class ReadFileRequest(BaseModel):
    path: Annotated[str, Field(description="Absolute file path inside the sandbox")]


class Type1(StrEnum):
    """
    Host type. Regular hosts are shared; BYOC hosts belong to a team.
    """

    regular = "regular"
    byoc = "byoc"


class CreateHostRequest(BaseModel):
    type: Annotated[
        Type1,
        Field(
            description="Host type. Regular hosts are shared; BYOC hosts belong to a team."
        ),
    ]
    team_id: Annotated[str | None, Field(description="Required for BYOC hosts.")] = None
    provider: Annotated[
        str | None,
        Field(description="Cloud provider (e.g. aws, gcp, hetzner, bare-metal)."),
    ] = None
    availability_zone: Annotated[
        str | None, Field(description="Availability zone (e.g. us-east, eu-west).")
    ] = None


class RegisterHostRequest(BaseModel):
    token: Annotated[
        str, Field(description="One-time registration token from POST /v1/hosts.")
    ]
    arch: Annotated[
        str | None, Field(description="CPU architecture (e.g. x86_64, aarch64).")
    ] = None
    cpu_cores: int | None = None
    memory_mb: int | None = None
    disk_gb: int | None = None
    address: Annotated[str, Field(description="Host agent address (ip:port).")]


class Type2(StrEnum):
    regular = "regular"
    byoc = "byoc"


class Status1(StrEnum):
    pending = "pending"
    online = "online"
    offline = "offline"
    draining = "draining"


class Host(BaseModel):
    id: str | None = None
    type: Type2 | None = None
    team_id: str | None = None
    provider: str | None = None
    availability_zone: str | None = None
    arch: str | None = None
    cpu_cores: int | None = None
    memory_mb: int | None = None
    disk_gb: int | None = None
    address: str | None = None
    status: Status1 | None = None
    last_heartbeat_at: AwareDatetime | None = None
    created_by: str | None = None
    created_at: AwareDatetime | None = None
    updated_at: AwareDatetime | None = None


class AddTagRequest(BaseModel):
    tag: str


class Error1(BaseModel):
    code: str | None = None
    message: str | None = None


class Error(BaseModel):
    error: Error1 | None = None


class CreateHostResponse(BaseModel):
    host: Host | None = None
    registration_token: Annotated[
        str | None,
        Field(
            description="One-time registration token for the host agent. Expires in 1 hour."
        ),
    ] = None


class RegisterHostResponse(BaseModel):
    host: Host | None = None
    token: Annotated[
        str | None,
        Field(
            description="Long-lived host JWT for X-Host-Token header. Valid for 1 year."
        ),
    ] = None
