# generated by datamodel-codegen:
#   filename:  openapi.yaml
#   timestamp: 2026-05-23T11:20:02+00:00

from __future__ import annotations
from pydantic import AwareDatetime, BaseModel, Field
from typing import Annotated
from enum import StrEnum


class Status(StrEnum):
    pending = "pending"
    starting = "starting"
    running = "running"
    pausing = "pausing"
    paused = "paused"
    snapshotting = "snapshotting"
    resuming = "resuming"
    stopping = "stopping"
    hibernated = "hibernated"
    stopped = "stopped"
    missing = "missing"
    error = "error"


class Capsule(BaseModel):
    id: str | None = None
    status: Status | None = None
    template: str | None = None
    vcpus: int | None = None
    memory_mb: int | None = None
    timeout_sec: int | None = None
    created_at: AwareDatetime | None = None
    started_at: AwareDatetime | None = None
    last_active_at: AwareDatetime | None = None
    last_updated: AwareDatetime | None = None
    metadata: Annotated[
        dict[str, str] | None,
        Field(
            description="Free-form key/value labels attached at create-time. Also carries\nagent-side version info (kernel_version, vmm_version,\nagent_version, envd_version) when running.\n"
        ),
    ] = None
    disk_size_mb: Annotated[
        int | None, Field(description="Maximum disk capacity in MiB.")
    ] = None
    disk_used_mb: Annotated[
        int | None,
        Field(
            description="Current disk usage in MiB. Only populated on individual capsule GET; omitted in list responses."
        ),
    ] = None


class Type(StrEnum):
    base = "base"
    snapshot = "snapshot"


class Template(BaseModel):
    name: str | None = None
    type: Type | None = None
    vcpus: int | None = None
    memory_mb: int | None = None
    size_bytes: int | None = None
    created_at: AwareDatetime | None = None
    platform: Annotated[
        bool | None,
        Field(
            description="True when the template is platform-managed (visible to all teams,\ne.g. the built-in `minimal-ubuntu` rootfs). False for team-owned\nsnapshot templates.\n"
        ),
    ] = None
    protected: Annotated[
        bool | None,
        Field(
            description="True for built-in system base templates (minimal-ubuntu,\nminimal-alpine, minimal-arch, minimal-fedora). Protected templates\ncannot be deleted.\n"
        ),
    ] = None
    metadata: dict[str, str] | None = None


class Type2(StrEnum):
    file = "file"
    directory = "directory"
    symlink = "symlink"


class FileEntry(BaseModel):
    name: str | None = None
    path: str | None = None
    type: Type2 | None = None
    size: int | None = None
    mode: int | None = None
    permissions: Annotated[
        str | None, Field(description='Human-readable permissions (e.g. "-rwxr-xr-x")')
    ] = None
    owner: str | None = None
    group: str | None = None
    modified_at: Annotated[
        int | None, Field(description="Unix timestamp (seconds)")
    ] = None
    symlink_target: str | None = None


class MakeDirResponse(BaseModel):
    entry: FileEntry | None = None


class ListDirResponse(BaseModel):
    entries: list[FileEntry] | None = None
